### PR TITLE
Update fcm.gemspec

### PR DESCRIPTION
**Pull request by qgzvcyxjfr**
[follow up on faraday 2](https://github.com/decision-labs/fcm/issues/99#issuecomment-1061620021):

[quote from the upgrade guide:](https://github.com/lostisland/faraday/blob/main/UPGRADING.md#thats-great-what-should-i-change-in-my-code-immediately-after-upgrading)

> That's great! What should I change in my code immediately after upgrading?
If you just use the default net_http adapter, then you don't need to do anything!

### CODE REVIEW

**Comment by sabman** [comment]
thanks @qgzvcyxjfr The tests seem to pass since we use the default adapter. Can someone else review this as well? @maszuDEV maybe?

**Comment by ahteshamtariq** [comment]
@sabman any tentative date or plan to release this?

**Comment by sabman** [comment]
@ahteshamtariq I was just waiting for any further feedback. If I don't hear any issues regarding this version I'll cut out a release by Monday. Hope that helps. If you get a chance to try it out please leave any feedback

**Comment by ahteshamtariq** [comment]
@sabman I have tested it with faraday 2.2.0 and it's working for me. But I've tried it only for the android platform. Looking forward to having reviews from others also.

**Comment by omarluq** [comment]
@sabman any ideas on when are you planning to release this 😃 ?

**Comment by noctivityinc** [comment]
@sabman +1 here.  With the release of Heroku's stack-22, we need to use Ruby 3.1, which is incompatible with the version of faraday that FCM requires.  If you update the gemspec to use the newer version then we will be all set

**Pull request merged**
